version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: node_container
    tty: true
    volumes:
      - ./:/app
    working_dir: "/app"
    ports:
      - 4000:4000
      - 9229:9229